"""
run_all.py
==========
Run the full verification suite (structural scaffold test + all numerical
cross-checks vs the lab's R/Julia code) and write a captured, reviewable
RESULTS.md. One command to re-verify the whole preprocessing layer:

    ./venv/Scripts/python tests/crosscheck/run_all.py
"""

from __future__ import annotations

import subprocess
import sys
from datetime import datetime
from pathlib import Path

HERE = Path(__file__).resolve().parent
TESTS = HERE.parent

SUITE = [
    ("Scaffold smoke test (structural)", TESTS / "test_scaffold.py"),
    ("Cross-check vs IdeaBio.R", HERE / "run_crosscheck_r.py"),
    ("Cross-check vs IdeaBio.jl", HERE / "run_crosscheck_jl.py"),
    ("imputePCA parity vs missMDA", HERE / "run_crosscheck_imputepca.py"),
]


def main():
    results = []
    sections = []
    for title, script in SUITE:
        print(f"\n### {title}  ({script.name})")
        proc = subprocess.run([sys.executable, str(script)], capture_output=True, text=True)
        ok = proc.returncode == 0
        results.append((title, script.name, ok))
        out = proc.stdout.rstrip()
        if proc.stderr.strip():
            out += "\n--- stderr ---\n" + proc.stderr.rstrip()
        print(out)
        print(f"--> {'PASS' if ok else 'FAIL'} (exit {proc.returncode})")
        sections.append((title, script.name, ok, proc.returncode, out))

    stamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "# Verification results (auto-generated by run_all.py)",
        "",
        f"_Last run: {stamp}_",
        "",
        "See README.md for what each harness checks and the decisions that came out.",
        "",
        "## Summary",
        "",
        "| suite | script | result |",
        "|-------|--------|--------|",
    ]
    for title, name, ok, _, _ in sections:
        lines.append(f"| {title} | `{name}` | {'PASS' if ok else 'FAIL'} |")
    lines.append("")
    for title, name, ok, code, out in sections:
        lines += [
            f"## {title}",
            f"`{name}` — {'PASS' if ok else 'FAIL'} (exit {code})",
            "",
            "```",
            out,
            "```",
            "",
        ]
    (HERE / "RESULTS.md").write_text("\n".join(lines), encoding="utf-8")

    n_pass = sum(1 for *_, ok in results)
    print("\n" + "=" * 60)
    print(f"{n_pass}/{len(results)} suites passed. Wrote {HERE / 'RESULTS.md'}")
    sys.exit(0 if n_pass == len(results) else 1)


if __name__ == "__main__":
    main()
